# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedetails',
            name='encrypted_data',
            field=models.CharField(default=10, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagedetails',
            name='key',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='messagedetails',
            name='message_data',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='messagedetails',
            name='protected',
            field=models.CharField(max_length=1000),
        ),
    ]
